version: "3.2"

services:

  # UKWA Heritrix
  heritrix-worker:
    image: ukwa/heritrix-worker
    ports:
      - 8443:8443
    environment:
      - "JAVA_OPTS=-Xmx2g"
      - "CRAWL_NAME=npld-fc"
      - "LAUNCH_AUTOMATICALLY=false"
      - "JOB_NAME=frequent"
      - "HERITRIX_USER=heritrix"
      - "HERITRIX_PASSWORD=test"
      - "CLAMD_HOST=clamd"
      - "KAFKA_BOOTSTRAP_SERVERS=kafka:9092"
      - "KAFKA_CRAWLED_TOPIC=frequent-crawl-log"
      - "KAFKA_TOCRAWL_TOPIC=uris-to-crawl"
      - "WRENDER_ENDPOINT=http://wrender:8010/render"
      - "CDXSERVER_ENDPOINT=http://cdxserver:8080/fc"

  # Hapy Dashboard
  hw-dash:
    build: .
    #image: ukwa/ukwa-manage:latest
    ports:
      - 8000:8000
    environment:
      - "HERITRIX_USERNAME=heritrix"
      - "HERITRIX_PASSWORD=test"
      - "CRAWL_JOBS_FILE=/ukwa-manage/dash/crawl-jobs-test.json"
    depends_on:
      - heritrix-worker
