version: "3.2"

services:

  # Hapy Dashboard
  hw-dash:
    build: .
    #image: ukwa/ukwa-manage:latest
    ports:
      - 8000:8000
    environment:
      - "HERITRIX_USERNAME=heritrix"
      - "HERITRIX_PASSWORD=test"
      - "CRAWL_JOBS_FILE=/ukwa-manage/dash/crawl-jobs-test.json"
      - "WEBHDFS_PREFIX=http://warc-server:8000/by-filename/"
      - "CDX_SERVER=http://cdx:9090/fc"
      - "KAFKA_BOOTSTRAP_SERVERS=kafka:9092"
      - "KAFKA_CRAWLED_TOPIC=uris.crawled.fc"
      - "KAFKA_SEEK_TO_BEGINNING=true"
    depends_on:
      - heritrix-worker
      - kafka

  # UKWA Heritrix
  heritrix-worker:
    image: ukwa/heritrix-worker
    ports:
      - 8443:8443
    environment:
      - "JAVA_OPTS=-Xmx2g"
      - "CRAWL_NAME=npld-fc"
      - "LAUNCH_AUTOMATICALLY=false"
      - "JOB_NAME=frequent"
      - "HERITRIX_USER=heritrix"
      - "HERITRIX_PASSWORD=test"
      - "CLAMD_HOST=clamd"
      - "KAFKA_BOOTSTRAP_SERVERS=kafka:9092"
      - "KAFKA_CRAWLED_TOPIC=frequent-crawl-log"
      - "KAFKA_TOCRAWL_TOPIC=uris-to-crawl"
      - "WRENDER_ENDPOINT=http://wrender:8010/render"
      - "CDXSERVER_ENDPOINT=http://cdxserver:8080/fc"

  # Kafka
  kafka:
    image: wurstmeister/kafka:1.1.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_NUM_RECOVERY_THREADS_PER_DATA_DIR: 10
      LOG_RETENTION_HOURS: -1
      LOG_RETENTION_BYTES: -1
      NUM_PARTITIONS: 128
      KAFKA_CREATE_TOPICS: "uris.tocrawl.fc:128:1 --config=compression.type=snappy,uris.crawled.fc:64:1 --config=compression.type=snappy,uris.discarded.fc:64:1 --config=compression.type=snappy"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      LOG4J_LOGGER_KAFKA: WARN
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  # Needs a Zookeeper too
  # ----
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
     - "2181:2181"

